name: Download and Commit

on:
  schedule:
    - cron: '0 0 * * *'  # 每天的0:00执行
  workflow_dispatch:  # 允许手动触发

jobs:
  download-and-commit:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'  # 选择 Python 版本

    - name: Install requests library
      run: |
        pip install requests zipfile

    - name: Download File
      run: python main.py  # 这里 main.py 负责下载文件

    - name: Get Current Date
      id: date
      run: echo "::set-output name=date::$(date +'%Y-%m-%d %H:%M:%S')"

    - name: Commit and Push
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add .
        git commit -m "Downloaded file on ${{ steps.date.outputs.date }}"
        git push
